# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
  };


  fileSystems."/boot" =
    {
      device = "/dev/disk/by-id/nvme-Samsung_SSD_980_500GB_S64DNF0RA83182Z_1-part3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  systemd.mounts = [
#    {
#      where = "/rendercache";
#      what = "/speed-storage/rendercache";
#      options = "bind";
#      after = [ "systemd-tmpfiles-setup.service" ];
#      wantedBy = [ "multi-user.target" ];
#    }
#    {
#      where = "/bulk-storage/nas-archive/remote.worker/88/88-FS-V2/rendercache";
#      what = "/speed-storage/rendercache";
#      options = "bind";
#      after = [ "systemd-tmpfiles-setup.service" ];
#      wantedBy = [ "multi-user.target" ];
#    }
    {
      where = "/var/tmp";
      what = "/speed-storage/tmp";
      options = "bind";
      after = [ "systemd-tmpfiles-setup.service" ];
      wantedBy = [ "multi-user.target" ];
    }
  ];
  fileSystems."/tmp" =
    {
      device = "speed-storage/tmp";
      fsType = "zfs";
    };
  fileSystems."/etc/ssh" =
    {
      device = "bulk-storage/etc-ssh";
      fsType = "zfs";
      options = [ "nofail" ];
    };
  fileSystems."/var/lib/tailscale" =
    {
      device = "bulk-storage/var-lib-tailscale";
      fsType = "zfs";
      options = [ "nofail" ];
    };
  fileSystems."/var/lib/libvirt" =
    {
      device = "speed-storage/var-lib-libvirt";
      fsType = "zfs";
      options = [ "nofail" ];
    };



  fileSystems."/nix" =
    {
      device = "speed-storage/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/8f73e910-ebff-49fa-9529-55bc0f06ceba";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/36875410-b2ca-4011-8c70-761c760677b8"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp69s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp69s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp72s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
