# modules/sysdiag.nix
# NixOS module for system diagnostics collection
#
# Deploys the sysdiag.sh script as a systemd oneshot service with optional
# periodic timer. All configuration is driven by Nix options rather than
# a runtime config file.
#
# Usage:
#   services.sysdiag.enable = true;          # Enable the tool
#   services.sysdiag.enableTimer = true;     # Enable hourly collection
#
# Ad-hoc run:
#   sudo sysdiag                              # Run immediately
#
# Two sub-services are provided:
#   services.sysdiag          — diagnostics collection
#   services.sysdiag-cleanup  — retention-based cleanup of old reports
{ config, lib, pkgs, ... }:

let
  cfg = config.services.sysdiag;
  cleanupCfg = config.services.sysdiag-cleanup;

  # ---------------------------------------------------------------------------
  # Generate env-to-collection-toggle mapping for the wrapper script
  # ---------------------------------------------------------------------------
  collectEnv = lib.mapAttrs'
    (name: enabled: {
      name = "SYSDIAG_COLLECT_${lib.toUpper name}";
      value = if enabled then "1" else "0";
    })
    cfg.collection;

  # ---------------------------------------------------------------------------
  # Wrapped diagnostics script
  #
  # Sets Nix-managed defaults via environment variables, then execs the
  # canonical sysdiag.sh (which reads those env vars with : "${VAR:=default}").
  #
  # This keeps the canonical script usable standalone (with its own defaults)
  # while the NixOS module overrides via environment.
  # ---------------------------------------------------------------------------
  sysdiagImpl = pkgs.writeShellScript "sysdiag.sh" (builtins.readFile ../system-diagnostics/sysdiag.sh);

  sysdiagWrapper = pkgs.writeShellScriptBin "sysdiag" ''
    #!/usr/bin/env bash
    # Wrapper generated by NixOS — exports configuration from Nix options
    # as environment variables, then runs the canonical sysdiag.sh
    set -euo pipefail

    # ---- Nix-managed configuration exports ----
    export SYSDIAG_OUTPUT_BASE="${cfg.outputBase}"
    ${lib.concatStringsSep "\n" (lib.mapAttrsToList (name: value: "export ${name}=\"${value}\"") collectEnv)}
    export SYSDIAG_JOURNAL_RECENT_LINES="${toString cfg.journalRecentLines}"
    export SYSDIAG_JOURNAL_ERROR_LINES="${toString cfg.journalErrorLines}"
    export SYSDIAG_JOURNAL_WARNING_LINES="${toString cfg.journalWarningLines}"
    export SYSDIAG_PROCESS_TOP_COUNT="${toString cfg.processTopCount}"
    export SYSDIAG_MAX_FILE_SIZE="${cfg.maxFileSize}"
    export SYSDIAG_MAX_TOTAL_SIZE="${cfg.maxTotalSize}"
    export SYSDIAG_COLLECT_BOOT_JOURNAL="${if cfg.collectBootJournal then "1" else "0"}"

    # Run the real script
    exec ${sysdiagImpl} "$@"
  '';

  # ---------------------------------------------------------------------------
  # Cleanup script
  # ---------------------------------------------------------------------------
  cleanupImpl = pkgs.writeShellScript "sysdiag-cleanup.sh" ''
    set -euo pipefail

    DIAG_BASE="''${SYSDIAG_OUTPUT_BASE:-/tmp}"
    PATTERN="sysdiag-*"
    RETENTION_DAYS="''${SYSDIAG_RETENTION_DAYS:-${toString cleanupCfg.retentionDays}}"
    RETENTION_COUNT="''${SYSDIAG_RETENTION_COUNT:-${toString cleanupCfg.retentionCount}}"

    log_info() { echo "[INFO] $*"; }

    find_diagnostic_dirs() {
      find "$DIAG_BASE" -maxdepth 1 -type d -name "$PATTERN" 2>/dev/null | sort -r
    }

    # Remove by age
    if [ "$RETENTION_DAYS" -gt 0 ]; then
      count=0
      log_info "Removing directories older than $RETENTION_DAYS days..."
      while IFS= read -r dir; do
        [ -z "$dir" ] && continue
        if [ "$(find "$dir" -maxdepth 0 -mtime +$RETENTION_DAYS -print 2>/dev/null)" ]; then
          log_info "Removing: $dir"
          rm -rf "$dir"
          ((count++))
        fi
      done < <(find_diagnostic_dirs)
      log_info "Removed $count directories by age"
    fi

    # Keep only most recent N
    if [ "$RETENTION_COUNT" -gt 0 ]; then
      dirs=()
      while IFS= read -r dir; do
        [ -n "$dir" ] && dirs+=("$dir")
      done < <(find_diagnostic_dirs)

      if [ "''${#dirs[@]}" -gt "$RETENTION_COUNT" ]; then
        to_remove=$(( ''${#dirs[@]} - RETENTION_COUNT ))
        for ((i=RETENTION_COUNT; i<''${#dirs[@]}; i++)); do
          log_info "Removing: ''${dirs[$i]}"
          rm -rf "''${dirs[$i]}"
        done
        log_info "Removed $to_remove directories by count"
      fi
    fi
  '';

  cleanupWrapper = pkgs.writeShellScriptBin "sysdiag-cleanup" ''
    #!/usr/bin/env bash
    set -euo pipefail
    export SYSDIAG_OUTPUT_BASE="${cfg.outputBase}"
    export SYSDIAG_RETENTION_DAYS="${toString cleanupCfg.retentionDays}"
    export SYSDIAG_RETENTION_COUNT="${toString cleanupCfg.retentionCount}"
    exec ${cleanupImpl} "$@"
  '';
in
{
  # ============================================================================
  # OPTIONS: services.sysdiag (diagnostics collection)
  # ============================================================================
  options.services.sysdiag = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable system diagnostics collection tool and systemd service";
    };

    outputBase = lib.mkOption {
      type = lib.types.str;
      default = "/tmp";
      example = "/var/log/sysdiag";
      description = ''
        Directory base where timestamped diagnostic output directories are created.
        Each run creates: <outputBase>/sysdiag-<hostname>-<timestamp>/
      '';
    };

    collection = lib.mkOption {
      type = lib.types.attrsOf lib.types.bool;
      default = {
        system = true;
        hardware = true;
        memory = true;
        disk = true;
        network = true;
        systemd = true;
        journal = true;
        kernel = true;
        processes = true;
        security = true;
        nixos = true;
        logs = true;
      };
      description = "Enable or disable individual collection categories";
      example = {
        system = true;
        hardware = false; # Skip hardware (slow, noisy)
        network = true;
        journal = true;
        kernel = true;
      };
    };

    journalRecentLines = lib.mkOption {
      type = lib.types.ints.positive;
      default = 1000;
      description = "Number of recent journalctl lines to collect";
    };

    journalErrorLines = lib.mkOption {
      type = lib.types.ints.positive;
      default = 500;
      description = "Number of journalctl error-level lines to collect";
    };

    journalWarningLines = lib.mkOption {
      type = lib.types.ints.positive;
      default = 500;
      description = "Number of journalctl warning-level lines to collect";
    };

    processTopCount = lib.mkOption {
      type = lib.types.ints.positive;
      default = 50;
      description = "Number of top processes to capture by CPU/memory";
    };

    maxFileSize = lib.mkOption {
      type = lib.types.str;
      default = "10M";
      example = "5M";
      description = "Maximum size per collected file (e.g., 10M, 5M, 1G)";
    };

    maxTotalSize = lib.mkOption {
      type = lib.types.str;
      default = "100M";
      example = "500M";
      description = "Maximum total size of the output directory";
    };

    collectBootJournal = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Collect full boot journal. WARNING: With debug logging enabled,
        boot journals can be 100MB+. Enable only when needed for debugging.
      '';
    };

    enableTimer = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable periodic collection via systemd timer";
    };

    timerConfig = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        OnBootSec = "5min";
        OnUnitActiveSec = "1h";
        RandomizedDelaySec = "5min";
        Persistent = "true";
      };
      example = {
        OnCalendar = "daily";
        Persistent = "true";
      };
      description = "Systemd timer configuration for periodic diagnostics collection";
    };

    securitySettings = lib.mkOption {
      type = lib.types.submodule {
        options = {
          protectSystem = lib.mkOption {
            type = lib.types.str;
            default = "strict";
            description = "ProtectSystem setting for the systemd service";
          };
          protectHome = lib.mkOption {
            type = lib.types.str;
            default = "read-only";
            description = "ProtectHome setting for the systemd service";
          };
          noNewPrivileges = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "NoNewPrivileges (must be false — script runs as root)";
          };
        };
      };
      default = { };
      description = "Security hardening for the systemd service unit";
    };
  };

  # ============================================================================
  # OPTIONS: services.sysdiag-cleanup (retention-based cleanup)
  # ============================================================================
  options.services.sysdiag-cleanup = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Enable periodic cleanup of old diagnostic reports";
    };

    retentionDays = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 30;
      example = 7;
      description = "Remove diagnostic directories older than this many days (0 to disable)";
    };

    retentionCount = lib.mkOption {
      type = lib.types.ints.unsigned;
      default = 10;
      example = 5;
      description = "Keep only this many most recent diagnostic directories (0 to disable)";
    };

    timerConfig = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        OnCalendar = "daily";
        Persistent = "true";
        RandomizedDelaySec = "30min";
      };
      description = "Systemd timer configuration for cleanup";
    };
  };

  # ============================================================================
  # CONFIG: diagnostics collection and cleanup
  # ============================================================================
  config = lib.mkMerge [
    # Diagnostics collection
    (lib.mkIf cfg.enable {
      # Install wrapper script into PATH for ad-hoc invocations
      environment.systemPackages = [ sysdiagWrapper ];

      # Ensure the output directory base exists
      systemd.tmpfiles.rules = [
        "d ${cfg.outputBase} 0755 root root -"
      ];

      # Oneshot service — collects diagnostics on each invocation
      systemd.services.sysdiag = {
        description = "System Diagnostics Collector";
        documentation = [ "https://github.com/your-org/sysdiag" ];
        after = [ "network.target" ];
        wants = [ "network.target" ];

        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${sysdiagWrapper}/bin/sysdiag";
          StandardOutput = "journal";
          StandardError = "journal";
          SyslogIdentifier = "sysdiag";

          # Security hardening
          NoNewPrivileges = cfg.securitySettings.noNewPrivileges;
          ProtectSystem = cfg.securitySettings.protectSystem;
          ProtectHome = cfg.securitySettings.protectHome;
          ReadWritePaths = [ cfg.outputBase ];
          PrivateTmp = false;

          # Resource limits
          LimitNOFILE = 65536;
          LimitNPROC = 4096;
        };
      };

      # Optional timer for periodic collection
      systemd.timers.sysdiag = lib.mkIf cfg.enableTimer {
        description = "Run System Diagnostics periodically";
        documentation = [ "https://github.com/your-org/sysdiag" ];
        timerConfig = cfg.timerConfig;
        wantedBy = [ "timers.target" ];
      };
    })

    # Cleanup service
    (lib.mkIf cleanupCfg.enable {
      environment.systemPackages = [ cleanupWrapper ];

      systemd.services.sysdiag-cleanup = {
        description = "Cleanup Old System Diagnostics Reports";
        documentation = [ "https://github.com/your-org/sysdiag" ];

        serviceConfig = {
          Type = "oneshot";
          ExecStart = "${cleanupWrapper}/bin/sysdiag-cleanup";
          StandardOutput = "journal";
          StandardError = "journal";
          SyslogIdentifier = "sysdiag-cleanup";
          NoNewPrivileges = true;
          ProtectSystem = "strict";
          ProtectHome = true;
          ReadWritePaths = [ cfg.outputBase ];
        };
      };

      systemd.timers.sysdiag-cleanup = {
        description = "Periodic cleanup of old system diagnostics reports";
        timerConfig = cleanupCfg.timerConfig;
        wantedBy = [ "timers.target" ];
      };
    })
  ];
}
