{
 "title": "CPU-Monitor-update",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "node_systemd_system_running", "legendFormat": "Systemd:{{instance}}" },
    {
     "expr": "node_scrape_collector_success{collector=\"systemd\", job=\"node\"}",
     "legendFormat": "Scrape:{{instance}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Data Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "idelta(node_ethtool_received_bytes_total[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "0 - idelta(node_ethtool_transmitted_bytes_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "node_hwmon_power_watt", "legendFormat": "{{instance}}" },
    {
     "expr": "node_power_supply_energy_watthour",
     "legendFormat": "{{instance}}"
    },
    { "expr": "nvidia_smi_power_draw_watts", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "General View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Disk RW Access",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "idelta(node_zfs_zpool_dataset_reads[5m]) > 512",
     "legendFormat": "{{instance}} {{dataset}}"
    },
    {
     "expr": "idelta(node_zfs_zpool_dataset_reads[5m]) > 512",
     "legendFormat": "{{instance}} {{dataset}}"
    },
    {
     "expr": "idelta(node_disk_read_bytes_total[5m]) > 512",
     "legendFormat": "{{instance}} - {{device}}"
    },
    {
     "expr": "idelta(node_disk_written_bytes_total[5m]) > 512",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "CPU - All Systems",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "idelta(node_cpu_seconds_total{mode!=\"idle\", job=\"node\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU - General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU - LINDA",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"10.88.127.88:9100\", job=\"node\"}",
     "legendFormat": "Core: {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU - Terminal-Zero",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"10.88.127.20:9100\", job=\"node\"}",
     "legendFormat": "Core: {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU -  Remote Systems",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "idelta(node_cpu_seconds_total{mode!=\"idle\", instance=\"10.88.127.50:9100\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "idelta(node_cpu_seconds_total{mode!=\"idle\", instance=\"10.88.127.51:9100\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU - cortex-alpha",
   "type": "heatmap",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"10.88.127.1:9100\", job=\"node\"}",
     "legendFormat": "Core: {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU - terminal-nx-01",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"10.88.127.21:9100\", job=\"node\"}",
     "legendFormat": "Core: {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU - Data-storage",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"10.88.127.3:9100\", job=\"node\"}",
     "legendFormat": "Core: {{cpu}}"
    }
   ]
  }
 ]
}