{
 "title": "Disk-usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GPU",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.88.127.88:9100\"}",
     "legendFormat": "MAX : {{instance}}"
    },
    {
     "expr": "node_memory_Active_bytes{instance=\"10.88.127.88:9100\"}",
     "legendFormat": "Current : {{instance}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "ZFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "idelta(node_zfs_zpool_dataset_reads{instance=\"10.88.127.88:9100\"}[5m])",
     "legendFormat": "{{instance}} {{dataset}}"
    },
    {
     "expr": "idelta(node_zfs_zpool_dataset_reads{instance=\"10.88.127.88:9100\"}[5m])",
     "legendFormat": "{{instance}} {{dataset}}"
    }
   ]
  }
 ]
}