# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #  fileSystems."/" =
  #    { device = "/dev/disk/by-uuid/ad9c9e74-4e20-498e-b2db-64fd4906b4ed";
  #      fsType = "ext4";
  #    };

  fileSystems."/etc/nixos" =
    {
      device = "bulk-storage/etc-nixos";
      fsType = "zfs";
    };

  fileSystems."/etc/ssh" =
    {
      device = "bulk-storage/etc-ssh";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    {
      device = "bulk-storage/var-log";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    {
      device = "bulk-storage/nix-store";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    {
      device = "bulk-storage/tmp";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/F05B-E22F";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/ccb735e9-0fd2-411c-86d2-5b3a38a96c29"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  networking = {
    defaultGateway = "181.215.32.33";
    nameservers = [ "1.1.1.1" "8.8.8.8" ];
    interfaces.enp2s0 = {
      ipv4.addresses = [{
        address = "181.215.32.40";
        prefixLength = 27;
      }];
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
