# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, self, modulesPath, ... }:

{
  imports =
    [
      ../../modifier_imports/bluetooth.nix
      ../../locale/home_networks.nix
      ../../environments/browsers.nix
      ../../environments/i3wm.nix
      ../../environments/rtl-sdr.nix
      ../../environments/pio.nix
      ../../environments/code.nix
      ../../locale/tailscale.nix
      ./hardware-configuration.nix
      ../../environments/steam.nix
      ../../lib/enable-wg.nix
      ../../lib/rclone-target.nix
    ];
  environment.systemPackages = with pkgs; [
    pkgs.moonlight-qt
  ];

  secrix.services.wireguard-wireg0.secrets.terminal-zero.encrypted.file = ../../secrets/wiregaurd/wg_terminal-zero;
  environment = {
    vpn =
      {
        enable = true;
        postfix = 20;
        privateKeyFile = config.secrix.services.wireguard-wireg0.secrets.terminal-zero.decrypted.path;
      };
    rclone-target = {
      enable = true;
      configFile = "${self}/secrets/rclone-config-file";
      targets = {
        obsidian-v3 = {
          filePath = "/home/pokej/88-DB-v3/";
          remoteName = "minio:obsidian-v3";
          syncInterval = 60; # every minute
        };
      };
    };
  };
  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot.loader =
    {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
  systemd.user.services.browser =
    {
      enable = true;
      description = "browser-autostart";
      wantedBy = [ "graphical-session.target" ];
      serviceConfig =
        {
          Restart = "always";
          ExecStart = ''
            ${lib.getExe pkgs.vivaldi}
          '';
          PassEnvironment = "DISPLAY XAUTHORITY";
        };
    };
  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.


  networking.firewall.allowedTCPPorts = [ 53 ];
  # Set a static IP on the "downstream" interface
  /* networking.firewall.extraCommands = ''
    # Set up SNAT on packets going from downstream to the wider internet
    iptables -t nat -A POSTROUTING -o wlp3s0 -j MASQUERADE

    # Accept all connections from downstream. May not be necessary
    iptables -A INPUT -i enp0s25 -j ACCEPT
  ''; */

  networking =
    {
      useDHCP = false;
      hostName = "Terminal-zero"; # Define your hostname.
      interfaces =
        {
          "enp0s25" = {
            useDHCP = true;
            #     ipv4.addresses = [{
            #       address = "10.0.0.1";
            #       prefixLength = 24;
            #     }];
          };
          wlp3s0.useDHCP = true;
          wwp0s29u1u4i6.useDHCP = true;
        };
      wireless =
        {
          enable = true; # Enables wireless support via wpa_supplicant.
          userControlled.enable = true;
          interfaces = [ "wlp3s0" ]; # NOT "wwp0s29u1u4i6" the gsm adapter
        };
    };

  # Enable CUPS to print documents.
  # Enable touchpad support (enabled default in most desktopManager).
  services =
    {
      libinput.enable = true;
      printing.enable = true;
    };

  # Enable sound.

  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
      vaapiVdpau
      libvdpau-va-gl
    ];
  };

}
