# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot =
    {
      supportedFilesystems = [ "ntfs" ];
      loader =
        {
          systemd-boot.enable = true;
          efi.canTouchEfiVariables = true;
        };
    };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking =
    {
      useDHCP = false;
      hostName = "TerminalVM2"; # Define your hostname.
      #    interfaces =
      #    {
      #      enp0s3.useDHCP = true;
      #    };
    };
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  virtualisation.hypervGuest.enable = true;

  boot =
    {
      initrd.availableKernelModules = [ "sd_mod" "sr_mod" ];
      initrd.kernelModules = [ ];
      kernelModules = [ ];
      extraModulePackages = [ ];
    };

  fileSystems = {
    "/" =
      {
        device = "/dev/disk/by-label/TerminalVM2";
        fsType = "ext4";
      };
    "/boot" =
      {
        device = "/dev/disk/by-label/VMBOOT";
        fsType = "vfat";
      };
  };

  swapDevices = [{ device = "/dev/disk/by-label/swapbox"; }];
  system.stateVersion = "21.11"; # Did you read the comment?
}
