# ------------------ CORTEX ALPHA -------------------
# this is my router gateway everything its bad plz look

# YEEEEEEEEEEE PAAAAINN :)
{
  config,
  lib,
  pkgs,
  self,
  hostname,
  ...
}:
let
  # Removed: proxyConfigs (now in real-topology/cortex-alpha.nix)
  # Removed: mkProxyPass (replaced by topology)
  nftableAttrs = {
    enp2s0.tcp = [
      {
        port = 2208;
        dest = "10.88.128.3:22";
      }
      {
        port = 27015;
        dest = "10.88.128.88:27015";
      }
      {
        port = 4549;
        dest = "10.88.128.88:4549";
      }
    ];
    enp2s0.udp = [
      {
        port = 17780;
        dest = "10.88.128.88:17780";
      }
      {
        port = 17781;
        dest = "10.88.128.88:17781";
      }
      {
        port = 17782;
        dest = "10.88.128.88:17782";
      }
      {
        port = 17783;
        dest = "10.88.128.88:17783";
      }
      {
        port = 17784;
        dest = "10.88.128.88:17784";
      }
      {
        port = 17785;
        dest = "10.88.128.88:17785";
      }
      {
        port = 27015;
        dest = "10.88.128.88:27015";
      }
      {
        port = 2207;
        dest = "10.88.127.88:2207";
      }
      {
        port = 4175;
        dest = "10.88.128.88:4175";
      }
      {
        port = 4179;
        dest = "10.88.128.88:4179";
      }
      {
        port = 4171;
        dest = "10.88.128.88:4171";
      }
    ];
  };
  mkNftables = import ../../lib/mkNftables.nix { inherit lib nftableAttrs; };
  # Removed: peerList (now in real-topology/cortex-alpha.nix)
  # Removed: dhcpHosts (now in real-topology/cortex-alpha.nix)
  # Removed: mkDhcpReservations (replaced by topology)
  # Removed: wgPeers (replaced by topology)
in

{
  imports = [
    #  ../../lib/network-interfaces.nix
    ../../services/dynamic_domain_gandi.nix
    (import ../../services/acme_server.nix { fqdn = "johnbargman.net"; })
    ../../server_services/ldap.nix
    ../../configuration.nix
    ../../locale/tailscale.nix
    ../../modules/core-router.nix
    # NOTE: enable-wg.nix is for WireGuard CLIENTS, not the hub
    # The hub's WireGuard config comes from core-router.nix via topology
    ./hardware-configuration.nix
    ../../modifier_imports/zfs.nix
  ];
  boot = {
    #  zfs.extraPools = [ "external" ];
    supportedFilesystems = [ "zfs" ];
    kernel = {
      sysctl = {
        "net.ipv4.conf.all.forwarding" = true;
        "net.ipv6.conf.all.forwarding" = false; # TODO: v6 please god
      };
    };
    loader.systemd-boot.enable = true;
    loader.efi.canTouchEfiVariables = true;
  };
  security.acme = {
    defaults.email = "commander@johnbargman.net";
    certs."johnbargman.net" = {
      extraDomainNames = [ "*.johnbargman.net" ]; # johnbargman.com"];
    };
  };
  # - here is my ideal senario
  # each system will, spread throughout the day, ipferf each other system.
  # just a small burst, so A ->B C->E etc
  # > "the iperf3 exporter does this it looks like, it will run iperf on demand" ~ @chloe.kever
  services.prometheus.exporters.dnsmasq = {
    enable = true;
    listenAddress = "10.88.127.1";
    port = 3101;
    leasesPath = "/dev/null";
    dnsmasqListenAddress = "10.88.128.1:53";
  };

  # NOTE: Proxy virtualHosts are now generated by core-router from topology
  # Only special vhosts that don't fit the topology pattern are defined here
  services.nginx.virtualHosts = {
    "_" = {
      default = true;
      listenAddresses = [
        "10.88.128.1"
        "10.88.127.1"
        "82.5.173.252"
      ];
      locations."/" = {
        return = "444"; # Close connection without response
      };
    };
    "johnbargman.net" = {
      enableACME = true;
      acmeRoot = null;
      forceSSL = true;
      listenAddresses = [
        "10.88.128.1"
        "10.88.127.1"
        "82.5.173.252"
      ];
      locations."/" = {
        root = ../../webroot;
        proxyWebsockets = false; # needed if you need to use websocket
      };
    };
    "cortex-alpha.johnbargman.net" = {
      useACMEHost = "johnbargman.net";
      forceSSL = true;
      listenAddresses = [
        "10.88.128.1"
        "10.88.127.1"
        "82.5.173.252"
      ]; # TODO: handle this assignment in a fixed fashion 82.5.173.252
      locations."/" = {
        root = ../../webroot;
        #proxyWebsockets = false; # needed if you need to use websocket
      };
    };
  };
  # so i'm thinking a 'port proxy' mother of all modules
  #  - TODO: the dream here is that i can have a list of source -> destination - type
  # - and map over that, outputting nginx proxies, port forwards, or port proxies
  #  - The possibilitites here are truely beyond imagining.
  # > "I would just converge the config of each system and map that in the module" ~ @Chloe.kever

  # Set your time zone.
  time.timeZone = "Etc/UTC";
  # NOTE: WireGuard config comes from core-router.nix via topology
  # NOTE: Tailscale config comes from core-router.nix via topology
  # WireGuard private key management via secrix
  secrix.services.wireguard-wireg0.secrets.cortex-alpha.encrypted.file =
    ../../secrets/private_keys/wireguard/wg_cortex-alpha;
  networking = {
    nat.enable = lib.mkForce false;
    nftables = {
      enable = true;
      ruleset = mkNftables;
    };
    #hostName = "cortex-alpha";
    hostId = "c043a1fa";
    # WireGuard private key - topology handles peers and IPs, but we need the key
    wireguard.interfaces.wireg0.privateKeyFile =
      config.secrix.services.wireguard-wireg0.secrets.cortex-alpha.decrypted.path;
    interfaces.enp3s0 = {
      useDHCP = lib.mkDefault false;
      ipv4.addresses = [
        {
          address = "10.88.128.1";
          prefixLength = 24;
        }
      ];
    };

    interfaces.enp2s0 = {
      useDHCP = lib.mkDefault true;
    };
  };

  # TODO: lift to common (modifier_imports/tailscale-udp-gro.nix) if needed later
  # This fix only applies to cortex-alpha for now
  environment.systemPackages = [ pkgs.ethtool ];
  systemd.services.tailscale-udp-gro = {
    description = "Enable UDP GRO forwarding for tailscale performance on enp2s0";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.ethtool}/bin/ethtool -K enp2s0 rx-udp-gro-forwarding on";
      RemainAfterExit = true;
    };
  };
}
