# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];


  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot =
  {
    loader =
    {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd =
    {
      availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    pulseaudio.enable = true;
    bluetooth.enable = true;
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking =
  {
    useDHCP = false;
    hostName = "Terminal-zero"; # Define your hostname.
    interfaces =
    {
      enp0s31f6.useDHCP = true;
      wlp4s0.useDHCP = true;
    };
    wireless =
    {
      enable = true;  # Enables wireless support via wpa_supplicant.
      userControlled.enable = true;
      interfaces = [ "wlp4s0" ];
    };
  };
  services = {
  printing.enable = true;
  blueman.enable = true;
  };
  # Enable sound.
  sound.enable = true;

  fileSystems  = {
    "/" =
    {
      device = "/dev/disk/by-label/nixos-linda";
      fsType = "ext4";
    };

    "/boot" =
    {
      device = "/dev/disk/by-label/LINDA-BOOT";
      fsType = "vfat";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-label/linda-swap"; }];

  # This value determines the NixOS release from which the default
  # settings for stateful data
  system.stateVersion = "21.05"; # Did you read the comment?
}
