# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
  environment.systemPackages = [
    pkgs.gwe
    pkgs.nvtop
  ];

  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot =
  {
    supportedFilesystems = [ "ntfs" ];
    loader =
    {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
    };
    initrd =
    {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod"  ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd"];
    kernelParams = [
    "processor.max_cstate=1"
    ];
    extraModulePackages = [ ];
  };

  powerManagement =
  {
    enable = false;
    cpuFreqGovernor = lib.mkDefault "performance";
  };
  services =
  {
    xserver =
    {
        libinput.enable = true;
        videoDrivers = [ "nvidia" ];
	deviceSection = ''
	  Option "Coolbits" "24"
	'';
    };
    printing = 
    { 
        enable = true;
        drivers = [ pkgs.epson-escpr ];
    };

  };
  hardware = {
    sane.enable = true;
    opengl.enable = true;
    pulseaudio.enable = true;
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl.driSupport32Bit = true;
    pulseaudio.support32Bit = true;
  };
  # Enable sound.
  sound.enable = true;

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking =
  {
    useDHCP = false;
    hostName = "LINDA"; # Define your hostname.
    interfaces =
    {
      enp69s0f0.useDHCP = true;
      enp69s0f1.useDHCP = true;
#      wlp72s0.useDHCP = true;
    };
# wireless disabled
#    wireless =
#    {
#      enable = true;  # Enables wireless support via wpa_supplicant.
#      userControlled.enable = true;
#      interfaces = [ "wlp72s0" ];
#    };
  };

  fileSystems =
  {
    "/" =
    {
      device = "/dev/disk/by-label/linda5-core";
      fsType = "ext4";
    };

    "/boot" =
    {
      device = "/dev/disk/by-label/LINDA5BOOT";
      fsType = "vfat";
    };
  };

  swapDevices = [ { device = "/dev/disk/by-label/linda5-swap"; }];

  # This value determines the NixOS release from which the default
  # settings for stateful data
  system.stateVersion = "21.11"; # Did you read the comment?
}
