# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot.loader =
  {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking =
  {
    useDHCP = false;
    hostName = "Terminal-media"; # Define your hostname.
    interfaces =
    {
      enp3s0.useDHCP = true;
      wlp4s0.useDHCP = true;
    };
    wireless =
    {
      enable = true;  # Enables wireless support via wpa_supplicant.
      userControlled.enable = true;
      interfaces = [ "wlp4s0"];
    };
  };

  # Enable CUPS to print documents.
  # Enable touchpad support (enabled default in most desktopManager).
  services =
  {
    xserver.libinput.enable = true;
    printing.enable = true;
  };

  # Enable sound.
  sound.enable = true;
  hardware.pulseaudio.enable = true;

  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "ums_realtek" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f75c01ea-9011-4660-87bc-9b37d69197ac";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0135-309F";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/121405c5-c42b-4282-9c79-ec627d1df674"; }
    ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, ... }:

