# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot.loader.grub. =
  {
    # Use the GRUB 2 boot loader.
    enable = true;
    version = 2;
    device = "/dev/sda"; # or "nodev" for efi only
  };

  # The global useDHCP flag is deprecated, therefore explicitly set to false here.
  # Per-interface useDHCP will be mandatory in the future, so this generated config
  # replicates the default behaviour.
  networking =
  {
    useDHCP = false;
    hostName = "TerminalVM1"; # Define your hostname.
    interfaces =
    {
      enp0s3.useDHCP = true;
    };
  };

  # Enable CUPS to print documents.
  services.printing.enable = true;

  # Enable sound.
  sound.enable = false;


  hardware.pulseaudio.enable = false;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  virtualisation.virtualbox.guest.enable = true;

  boot =
  {
    initrd.availableKernelModules = [ "ata_piix" "ohci_pci" "sd_mod" "sr_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [  ];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/TerminalVM1";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-label/swapbox"; } ];
  system.stateVersion = "21.11"; # Did you read the comment?
}
