# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, self, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../lib/enable-wg.nix
  ];
  secrix.services.wireguard-wireg0.secrets.nx-01.encrypted.file = ../../secrets/wg_terminal-nx-01;
  environment.vpn =
    {
      enable = true;
      postfix = 21;
      privateKeyFile = config.secrix.services.wireguard-wireg0.secrets.nx-01.decrypted.path;
    };
  environment.systemPackages = [
    pkgs.google-chrome
    pkgs.brave
    pkgs.moonlight-qt
  ];

  systemd.user.services.browser =
    {
      enable = true;
      description = "browser-autostart";
      wantedBy = [ "graphical-session.target" ];
      serviceConfig =
        {
          Restart = "always";
          ExecStart = ''
            ${lib.getExe pkgs.google-chrome}
          '';
          PassEnvironment = "DISPLAY XAUTHORITY";
        };
    };

  # Use the GRUB 2 boot loader.
  # Use the systemd-boot EFI boot loader.
  boot.loader = {
    systemd-boot.enable = true;
    efi.canTouchEfiVariables = true;
  };



  networking = {
    firewall.allowedUDPPorts = [ 2108 ];
    useDHCP = false;
    hostName = "terminal-nx-01"; # Define your hostname.
    interfaces = {
      enp4s0.useDHCP = true;
      wlp3s0.useDHCP = true;
    };
    wireless = {
      enable = true; # Enables wireless support via wpa_supplicant.
      userControlled.enable = true;
      interfaces = [ "wlp3s0" ];
    };
  };

  # Enable CUPS to print documents.
  # Enable touchpad support (enabled default in most desktopManager).
  hardware.graphics.enable = true;
  hardware.nvidia.modesetting.enable = true;
  services = {
    libinput.enable = true;
    xserver = {
      videoDrivers = [ "nvidia" ];
    };
    printing.enable = true;
  };

  hardware.nvidia = {
    package = config.boot.kernelPackages.nvidiaPackages.legacy_470;
    prime = {

      sync.enable = true;

      # Bus ID of the NVIDIA GPU. You can find it using lspci, either under 3D or VGA
      nvidiaBusId = "PCI:1:0:0";

      # Bus ID of the Intel GPU. You can find it using lspci, either under 3D or VGA
      intelBusId = "PCI:0:2:0";
    };
  };

  # Enable sound.
  #hardware.sound.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "ums_realtek"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f75c01ea-9011-4660-87bc-9b37d69197ac";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0135-309F";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/121405c5-c42b-4282-9c79-ec627d1df674"; }];

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
