# Minecraft CurseForge Server Builder — Fixed-Output Derivation
#
# This builder fetches a CurseForge server pack zip, extracts it, runs the
# modpack's setup script, patches the start script to use a Nix-aware JRE,
# and produces an immutable server fabric.
#
# The output is a fixed-output derivation: network access is allowed during
# the build (for the setup script to download dependencies), but the output
# hash must match exactly.
#
# Usage:
#   minecraft-curseforge {
#     name = "atm10";
#     src = fetchurl { url = "..."; hash = "sha256-..."; };
#     outputHash = "sha256-...";
#   }
#
# The `outputHash` is the hash of the FINAL output directory contents. On
# first build, Nix will suggest the correct hash after a failed attempt.

{ stdenv
, lib
, unzip
, jdk21
}:

# Curried: outer args are build-time deps, inner args are per-pack config
{ name
, src
, jre ? jdk21
, outputHash
, # Names of setup scripts to probe for, in priority order.
  # The first existing script found will be executed.
  setupScripts ? [
    "server-setup.sh"
    "ServerStart.sh"
    "LaunchServer.sh"
    "start_server.sh"
  ]
}:

let
  # Image identity: derived from the fetchurl store path basename.
  # This propagates through the derivation chain for update detection.
  imageId = builtins.baseNameOf src;
in
stdenv.mkDerivation {
  pname = "minecraft-server-builder-${name}";
  version = "unstable";

  inherit src;

  nativeBuildInputs = [
    unzip
  ];

  # JRE in buildInputs (not nativeBuildInputs) — ensures it's in the
  # runtime closure. The patched start.sh references ${jre}/bin/java,
  # and Nix's reference scanner finds this text reference in the output.
  buildInputs = [
    jre
  ];

  # Fixed-output: network access allowed during build
  outputHashMode = "recursive";
  inherit outputHash;

  # Expose imageId and jre without building the derivation
  passthru = { inherit imageId jre; };

  # CRITICAL: Single buildPhase — patchPhase runs BEFORE buildPhase in
  # Nix's mkDerivation, so it cannot reference files that don't exist yet.
  # All work happens here: extract, setup, strip, patch, identity.
  buildPhase = ''
    runHook preBuild

    # ── Extract modpack ──────────────────────────────────────────────
    unzip "$src" -d "$out"
    cd "$out"

    # ── Probe for setup script ───────────────────────────────────────
    setupScript=""
    for script in ${lib.concatStringsSep " " setupScripts}; do
      if [ -f "$script" ]; then
        setupScript="$script"
        break
      fi
    done

    if [ -z "$setupScript" ]; then
      echo "ERROR: No recognized setup script found in modpack!"
      echo "Searched for: ${lib.concatStringsSep ", " setupScripts}"
      echo "Files in archive:"
      ls -la "$out/"
      exit 1
    fi

    echo "Using setup script: $setupScript"

    # ── Run setup (pipe yes for interactive prompts) ─────────────────
    yes | bash "$setupScript"

    # ── Strip module-owned files ─────────────────────────────────────
    # These will be provided by the overlay derivation (Phase 2).
    rm -f "$out/eula.txt" "$out/server.properties"
  '';

  # postBuild runs AFTER buildPhase — safe to rewrite start.sh here.
  # This ensures the script exists (created by setup or by us).
  postBuild = ''
    # ── Rewrite start script ─────────────────────────────────────────
    # Discover the actual launcher JAR (varies by modpack)
    launcherJar=""
    for jar in server.jar forge.jar neoforge.jar fabric-server-launch.jar; do
      if [ -f "$out/$jar" ]; then
        launcherJar="$out/$jar"
        break
      fi
    done

    if [ -z "$launcherJar" ]; then
      echo "WARNING: No recognized server JAR found. Searching for any .jar..."
      launcherJar=$(find "$out" -maxdepth 1 -name "*.jar" -type f | head -1)
      if [ -z "$launcherJar" ]; then
        echo "ERROR: No .jar files found in modpack output!"
        exit 1
      fi
    fi

    echo "Using launcher: $launcherJar"

    # Write the nix-aware start script
    # NOTE: ''${} in Nix's '' strings produces literal ${} in the output,
    # which bash then interprets as variable expansion.
    cat > "$out/start.sh" << STARTSCRIPT
#!${stdenv.shell}
# Auto-generated by minecraft-curseforge builder — do not edit
# Environment variables:
#   JAVA_MAX_MEM  - Maximum heap size (default: 4G)
#   JAVA_MIN_MEM  - Minimum heap size (default: 2G)
#   JAVA_OPTS     - Additional JVM arguments

exec ${jre}/bin/java \
  -Xmx''${JAVA_MAX_MEM:-4G} \
  -Xms''${JAVA_MIN_MEM:-2G} \
  ''${JAVA_OPTS:-} \
  -jar "$launcherJar" nogui
STARTSCRIPT
    chmod +x "$out/start.sh"

    # ── Write image identity ─────────────────────────────────────────
    echo -n "${imageId}" > "$out/.image-id"

    # ── Strip CurseForge metadata if present ─────────────────────────
    rm -rf "$out/.curseforge" "$out/overrides" 2>/dev/null || true
  '';

  # No installPhase — the entire $out directory IS the output.
  installPhase = "true";

  meta = with lib; {
    description = "Builder for Minecraft CurseForge server packs";
    license = licenses.free; # CurseForge packs have their own licenses
    platforms = platforms.linux;
    maintainers = [ ];
  };
}
